environment:
  global:
    HDF_DIR: "C:/Program Files (x86)/HDF_Group/HDF5/1.8.17/lib"
    BOOST_ROOT: C:\Libraries\boost_1_67_0

  matrix:
    # - PYTHON: "C:\\Python27-x64"
    #   PYTHON_VERSION: "2.7.12"
    #   PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.5"
      PYTHON_ARCH: "64"
      
init:
  - cmd: cmake --version

install:
  - if "%PYTHON_VERSION%" == "3.6.5" set PATH=C:\Miniconda36-x64;C:\Miniconda36-x64\Scripts;%PATH%
  - conda install -y -n root conda-build
  - if "%PYTHON_VERSION%" == "3.6.5" ls C:\Miniconda36-x64
  - conda skeleton pypi autopep8
  - ls
  - ls autopep8
  - conda build autopep8
  - if "%PYTHON_VERSION%" == "3.6.5" ls C:\Miniconda36-x64\conda-bld

build: false

branches:
  only:
    - master

# artifacts:
# - path: =C:\Miniconda36-x64\conda-bld\linux-64
