environment:
  global:
    # HDF_DIR: "C:/Program Files (x86)/HDF_Group/HDF5/1.8.17/lib"
    # BOOST_ROOT: C:\Libraries\boost_1_67_0

  matrix:
    # - PYTHON: "C:\\Python27-x64"
    #   PYTHON_VERSION: "2.7.12"
    #   PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.5"
      PYTHON_ARCH: "64"
      
init:
  # - cmd: cmake --version

install:
  - if "%PYTHON_VERSION%" == "3.6.5" set MINICONDAPATH=C:\Miniconda36-x64
  - set PATH=%MINICONDAPATH%;%MINICONDAPATH%\Scripts;%PATH%
  - conda install -y -n root conda-build
  - ls %MINICONDAPATH%
  - conda skeleton pypi autopep8
  - ls
  - ls autopep8
  - conda build autopep8
  - ls %MINICONDAPATH%\conda-bld

build: false

branches:
  only:
    - master

artifacts:
  - path: C:\Miniconda36-x64\conda-bld\win-64
